# Generated by Django 4.2.6 on 2023-10-20 07:50

import Profile.models.base_profile_model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            (
                                Profile.models.base_profile_model.UserType["ADMIN"],
                                "admin",
                            ),
                            (
                                Profile.models.base_profile_model.UserType["ORGANIZER"],
                                "organizer",
                            ),
                            (
                                Profile.models.base_profile_model.UserType["ATTENDEE"],
                                "attendee",
                            ),
                            (
                                Profile.models.base_profile_model.UserType["SPEAKER"],
                                "speaker",
                            ),
                            (
                                Profile.models.base_profile_model.UserType["VENDOR"],
                                "vendor",
                            ),
                            (
                                Profile.models.base_profile_model.UserType["STAFF"],
                                "staff",
                            ),
                            (
                                Profile.models.base_profile_model.UserType["SPONSOR"],
                                "sponsor",
                            ),
                        ],
                        default=Profile.models.base_profile_model.UserType["ATTENDEE"],
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "ticket_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "organization_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("expertise", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("staff_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "sponsor_level",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
